<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Aspire.AppHost.Sdk" Version="13.4.6" />


  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>9943a303-fd9b-46b7-be56-1f8e2f42497d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.4.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UserDBService\UserDBService.csproj" />
    <ProjectReference Include="..\ReviewDBService\ReviewDBService.csproj" />
    <ProjectReference Include="..\ServiceDBService\ServiceDBService.csproj" />
    <ProjectReference Include="..\PaymentDBService\PaymentDBService.csproj" />
    <ProjectReference Include="..\BookingDBService\BookingDBService.csproj" />
    <ProjectReference Include="..\RoomDBService\RoomDBService.csproj" />
    <ProjectReference Include="..\IdentityDBService\IdentityDBService.csproj" />
    <ProjectReference Include="..\NotificationDBService\NotificationDBService.csproj" />
    <ProjectReference Include="..\CustomerDBService\CustomerDBService.csproj" />
  </ItemGroup>

</Project>
